CATEGORY = [
    'Art',
    'Business',
    'Charity',
    'Community',
    'Education',
    'Entertainment',
    'Fashion',
    'Food & Drink',
    'Film & Media',
    'Lifestyle',
    'Science & Tech',
    'Sports & Fitness',
    'Travel',
    'Other',
]